### ISSUE TITLE
Cesium Map - blue MyLocation button and zoom level

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [worldpeaceenginelabs/PWA-SPA-LOGIN-MAINSCREEN-MENU-Starter-Kit#10]
# Now:
When the app starts, the camera zooms automatically on the user's position.

# After:

## When starting the app
- The planet hovers in space rotating. (**zoom_level_start, globe_rotate_speed**)
- The map shows the user's position with a pulsating blue dot constantly but does not zoom in. (picture)

## The home button symbol is replaced with a location symbol
- First click/tap = camera zooms on the user's position (zoom level 12) (**zoom_level_user**)
- Second click/tap  = camera zooms out on the rotating planet (**zoom_level_start**)

## The values of the three bold marked "variables" are accessible in [app.config.json](https://github.com/worldpeaceenginelabs/PWA-SPA-LOGIN-MAINSCREEN-MENU-Starter-Kit/blob/main/app.config.json) so that someone is easily able to fine-tune the Cesium related settings, without having to jump between multiple files. 

![image](https://user-images.githubusercontent.com/67427045/123496415-40da0d00-d628-11eb-9c02-d04965d088ac.png)

**Comment by t-moennich** [comment]
@worldpeaceenginelabs what exactly do you mean with the following:

>The planet hovers in space rotating. (zoom_level_start, globe_rotate_speed)

Should the globe auto rotate while the user mouse hovers the space and stops rotating if the globe is hovered?
This of cause will only work on desktop
